### הוספת פוסט חדש
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "The post of Guy",
    "content": "Hi, my name is Guy!",
    "sender": "guy"
}

### קבלת כל הפוסטים
GET http://localhost:3000/posts

### קבלת פוסט לפי ID
GET http://localhost:3000/posts/679089de575ad2c8657a57b6

### קבלת פוסטים לפי מזהה שולח
GET http://localhost:3000/posts?sender=guy

### עדכון פוסט
PUT http://localhost:3000/posts/679089de575ad2c8657a57b6
Content-Type: application/json

{
    "title": "Updated Post Titleaaaaaaaaaaa",
    "content": "Updated content of the post."
}

### מחיקת פוסט
DELETE http://localhost:3000/posts/679089de575ad2c8657a57b6


////////////////////////////////////////////////////////////////////////////////// 
////////////////////////////////////////////////////////////////////////////////// 


### Add a New Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "679089de575ad2c8657a57b6",
    "content": "This is comment from ami to guy! 2 ",
    "commenter": "ami"
}

### Get All Comments for a Post
GET http://localhost:3000/comments/679089de575ad2c8657a57b6

### Update a Comment
PUT http://localhost:3000/comments/679089fd575ad2c8657a57be
Content-Type: application/json

{
    "content": "Updated comment content."
}

### Delete a Comment
DELETE http://localhost:3000/comments/679089fd575ad2c8657a57be
