### הוספת פוסט חדש
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My second post",
    "content": "This is the content of the post.",
    "sender": "ami"
}

### קבלת כל הפוסטים
GET http://localhost:3000/posts

### קבלת פוסט לפי ID
GET http://localhost:3000/posts/673b7969a77f9a809d2dfd38

### קבלת פוסטים לפי מזהה שולח
GET http://localhost:3000/posts?sender=ami

### עדכון פוסט
PUT http://localhost:3000/posts/673b7969a77f9a809d2dfd38
Content-Type: application/json

{
    "title": "Updated Post Titleaaaaaaaaaaa",
    "content": "Updated content of the post."
}

### מחיקת פוסט
DELETE http://localhost:3000/posts/id id id id idi d 


////////////////////////////////////////////////////////////////////////////////// 
////////////////////////////////////////////////////////////////////////////////// 


### Add a New Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "673b7969a77f9a809d2dfd38",
    "content": "This is a comment 222.",
    "commenter": "commenter123"
}

### Get All Comments for a Post
GET http://localhost:3000/comments/673b7969a77f9a809d2dfd38

### Update a Comment
PUT http://localhost:3000/comments/673b8a58bd1aa1bbc53c769f
Content-Type: application/json

{
    "content": "Updated comment content."
}

### Delete a Comment
DELETE http://localhost:3000/comments/673b8a21bd1011bbc53c769b
